PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO cms_pages (id, slug, title, status, body_json, seo_title, seo_description, canonical_path, published_at)
VALUES
  ('page-home', 'home', 'Dakzo Systems', 'published',
   '{"heroEyebrow":"A Dakik LLC Company","heroTitle":"We build systems that run businesses.","intro":"Dakzo Systems designs and builds custom software, ERP platforms, web applications, mobile applications, logistics technology, tracking systems, and business automation.","featuredProjectSlug":"hmd-erp","sections":[{"heading":"Selected work","body":"HMD ERP, Congo Delivery, and Moto Track demonstrate how Dakzo turns operational requirements into working software."},{"heading":"Built around operations","body":"We design products around real workflows, clear interfaces, dependable engineering, and long-term maintainability."}],"primaryCta":{"label":"Start a project","href":"/contact/"},"secondaryCta":{"label":"See our work","href":"/work/"}}',
   'Dakzo Systems | Custom Software, ERP & Applications',
   'Dakzo Systems builds custom software, ERP platforms, web and mobile applications, logistics technology, tracking systems, and business automation.',
   '/', CURRENT_TIMESTAMP),
  ('page-about', 'about', 'About Dakzo Systems', 'published',
   '{"heroEyebrow":"About Dakzo","heroTitle":"Technology built for real operations.","intro":"Dakzo Systems is the software and technology subsidiary of Dakik LLC, focused on designing and building digital systems, products, and platforms.","featuredProjectSlug":"","sections":[{"heading":"What we build","body":"Custom software, ERP, business systems, websites, applications, logistics technology, tracking platforms, and automation."},{"heading":"How we work","body":"We combine product thinking, interface design, business logic, and engineering around the operating reality of each project."}],"primaryCta":{"label":"View our work","href":"/work/"},"secondaryCta":{"label":"Start a project","href":"/contact/"}}',
   'About Dakzo Systems | A Dakik LLC Company',
   'Learn about Dakzo Systems, the software and technology subsidiary of Dakik LLC building custom digital systems and applications.',
   '/about/', CURRENT_TIMESTAMP),
  ('page-services', 'services', 'Dakzo Systems Services', 'published',
   '{"heroEyebrow":"Services","heroTitle":"Software engineering around your business.","intro":"Dakzo Systems builds custom digital products from operational discovery through design, engineering, deployment, and iteration.","featuredProjectSlug":"hmd-erp","sections":[{"heading":"Custom software","body":"Purpose-built systems for workflows that generic tools do not fit."},{"heading":"ERP and business systems","body":"Inventory, finance, operations, logistics, reporting, production, and connected workflows."},{"heading":"Web and mobile applications","body":"Responsive products designed for real users across desktop, tablet, and mobile."}],"primaryCta":{"label":"Start a project","href":"/contact/"},"secondaryCta":{"label":"Explore solutions","href":"/solutions/"}}',
   'Software Development Services | Dakzo Systems',
   'Explore Dakzo Systems services for custom software, ERP platforms, web applications, mobile applications, logistics systems, and automation.',
   '/services/', CURRENT_TIMESTAMP),
  ('page-solutions', 'solutions', 'Dakzo Systems Solutions', 'published',
   '{"heroEyebrow":"Solutions","heroTitle":"Systems designed around the way work actually happens.","intro":"We create digital systems for operations, logistics, inventory, tracking, finance, delivery, and business automation.","featuredProjectSlug":"congo-delivery","sections":[{"heading":"ERP and operations","body":"Connected business workflows spanning data, approvals, reporting, stock, finance, and teams."},{"heading":"Logistics and delivery","body":"Dispatch, tracking, operational visibility, customer workflows, and logistics coordination."},{"heading":"Tracking platforms","body":"Maps, assets, alerts, history, reporting, and mobile operational visibility."}],"primaryCta":{"label":"View selected work","href":"/work/"},"secondaryCta":{"label":"Talk to Dakzo","href":"/contact/"}}',
   'Business Software Solutions | Dakzo Systems',
   'Dakzo Systems creates ERP, logistics, tracking, inventory, delivery, and business automation solutions built around real operations.',
   '/solutions/', CURRENT_TIMESTAMP),
  ('page-contact', 'contact', 'Start a Project | Dakzo Systems', 'published',
   '{"heroEyebrow":"Start a project","heroTitle":"Tell us what you need to build.","intro":"Share the problem, workflow, product idea, timeline, and requirements. Dakzo can turn the brief into a structured software project.","featuredProjectSlug":"","sections":[{"heading":"Good starting information","body":"Describe the users, workflow, current problem, desired result, important integrations, timeline, and any existing system constraints."}],"primaryCta":{"label":"Explore our work","href":"/work/"},"secondaryCta":{"label":"About Dakzo","href":"/about/"}}',
   'Start a Software Project | Dakzo Systems',
   'Start a custom software, ERP, web application, mobile application, logistics, tracking, or automation project with Dakzo Systems.',
   '/contact/', CURRENT_TIMESTAMP);

INSERT OR IGNORE INTO cms_articles (id, slug, title, excerpt, status, content_json, seo_title, seo_description, published_at)
VALUES
  ('article-custom-erp', 'custom-erp-vs-off-the-shelf', 'Custom ERP vs. off-the-shelf ERP',
   'A practical framework for deciding whether a business should adapt to packaged ERP software or invest in a system designed around its operations.',
   'published',
   '{"category":"ERP","body":"Off-the-shelf ERP can be a strong fit when a company follows standard processes and wants faster implementation. Custom ERP becomes more valuable when operations contain unique workflows, integrations, permissions, costing logic, or reporting needs that generic software forces the business to work around.\n\nThe decision should compare long-term operational fit, implementation risk, change management, integration requirements, ownership, and the cost of maintaining workarounds.","relatedProjectSlug":"hmd-erp","takeaways":["Choose based on operational fit, not feature count.","Include integration and workflow costs in the comparison.","Custom ERP is strongest when unique processes create real competitive or operational value."]}',
   'Custom ERP vs Off-the-Shelf ERP | Dakzo Systems',
   'Compare custom ERP and off-the-shelf ERP by operational fit, integrations, workflow complexity, ownership, implementation, and long-term value.', CURRENT_TIMESTAMP),
  ('article-custom-software', 'when-custom-software-is-worth-it', 'When custom software is worth it',
   'How to recognize when spreadsheets, disconnected tools, or rigid SaaS products are creating enough operational friction to justify custom software.',
   'published',
   '{"category":"Custom Software","body":"Custom software is most valuable when a recurring operational problem cannot be solved cleanly with existing products. Warning signs include repeated manual reconciliation, duplicate data entry, fragile spreadsheets, permission gaps, disconnected systems, and workflows that employees must constantly work around.\n\nA strong custom-software project starts with the business process and measurable operating problem rather than a list of desired screens.","relatedProjectSlug":"hmd-erp","takeaways":["Start with the operating problem.","Measure the cost of the current workaround.","Build the smallest system that removes meaningful friction first."]}',
   'When Custom Software Is Worth It | Dakzo Systems',
   'Learn when custom software makes business sense and how to evaluate workflow friction, manual work, integrations, risk, and long-term value.', CURRENT_TIMESTAMP),
  ('article-logistics', 'how-logistics-platforms-work', 'How logistics platforms connect operations',
   'A look at how modern logistics platforms connect order intake, dispatch, tracking, operational visibility, and customer workflows.',
   'published',
   '{"category":"Logistics Technology","body":"A logistics platform becomes useful when it creates one operating picture across orders, dispatch, vehicles or riders, status changes, exceptions, and customer communication. The system should reduce the number of places where teams must check or re-enter the same information.\n\nGood logistics software also makes responsibility and state transitions clear, so operators know what is waiting, assigned, moving, delayed, completed, or needs attention.","relatedProjectSlug":"congo-delivery","takeaways":["Connect order, dispatch, and tracking states.","Make exceptions visible early.","Design the interface around operators as well as customers."]}',
   'How Logistics Platforms Work | Dakzo Systems',
   'Understand how logistics software connects order intake, dispatch, tracking, operational visibility, exceptions, and customer communication.', CURRENT_TIMESTAMP),
  ('article-fleet-tracking', 'how-fleet-tracking-systems-work', 'How fleet tracking systems work',
   'The core product and operational components behind fleet and motorcycle tracking systems, from location events to alerts, history, and reporting.',
   'published',
   '{"category":"Tracking Technology","body":"Fleet tracking software turns a stream of location and device events into operational information. The useful product is not only a moving dot on a map; it includes asset identity, current state, history, alerts, search, reporting, permissions, and mobile access.\n\nThe best tracking interfaces help operators understand what changed and what action is needed without overwhelming them with raw telemetry.","relatedProjectSlug":"moto-track","takeaways":["Tracking is an operational workflow, not only a map.","History and alerts are as important as current position.","Design around decisions operators need to make."]}',
   'How Fleet Tracking Systems Work | Dakzo Systems',
   'Learn how fleet tracking systems combine location events, maps, alerts, history, reporting, permissions, and operational workflows.', CURRENT_TIMESTAMP);
