export function renderAdminPage({ email, storageReady }) {
  const status = storageReady ? 'Connected' : 'Schema ready · D1 binding pending';
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Dakzo Admin</title><style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#08101d;color:#edf4ff}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at top right,#12345a 0,#08101d 42%)}a{color:inherit}.shell{display:grid;grid-template-columns:260px 1fr;min-height:100vh}.side{padding:28px 22px;border-right:1px solid #26364c;background:#0a1321dd}.brand{font-size:20px;font-weight:800}.brand small{display:block;margin-top:4px;color:#8ea4c0;font-size:12px;font-weight:600}.nav{display:grid;gap:8px;margin-top:34px}.nav a{padding:12px 14px;border-radius:10px;text-decoration:none;color:#afbdd0}.nav a.active{background:#15243a;color:#fff}.main{padding:42px;max-width:1180px;width:100%}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.eyebrow{color:#72d7ff;font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.12em}h1{font-size:clamp(32px,5vw,56px);margin:10px 0 12px}.muted{color:#9eb0c7;max-width:720px;line-height:1.6}.user{padding:10px 13px;border:1px solid #2e425f;border-radius:999px;color:#bed0e5;font-size:13px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:34px}.card{padding:22px;border:1px solid #263b57;border-radius:18px;background:#0c1727cc}.card h2{font-size:18px;margin:10px 0 8px}.card p{color:#9db0c7;line-height:1.5;margin:0}.pill{display:inline-block;padding:5px 9px;border-radius:999px;background:#16344a;color:#89ddff;font-size:11px;font-weight:800}.status{margin-top:34px;padding:18px 20px;border:1px solid #294460;border-radius:14px;background:#0b1b2b}.status strong{display:block;margin-bottom:6px}@media(max-width:780px){.shell{grid-template-columns:1fr}.side{border-right:0;border-bottom:1px solid #26364c}.nav{grid-template-columns:repeat(2,minmax(0,1fr));margin-top:18px}.main{padding:28px 20px}.top{display:block}.user{display:inline-block;margin-top:14px}.grid{grid-template-columns:1fr}}
</style></head><body><div class="shell"><aside class="side"><div class="brand">Dakzo Systems<small>Private Admin</small></div><nav class="nav" aria-label="Admin navigation"><a class="active" href="/admin/">Dashboard</a><a href="#pages">Pages</a><a href="#projects">Projects</a><a href="#insights">Insights</a><a href="#media">Media</a><a href="#settings">Settings</a></nav></aside><main class="main"><div class="top"><div><div class="eyebrow">CMS foundation</div><h1>Website control center.</h1><p class="muted">The private Dakzo CMS is now separated from the public website. Phases 1–2 establish structured content, a protected admin boundary, and the data contract that later editors and media tools will use.</p></div><span class="user">${escapeHtml(email)}</span></div><section class="grid" aria-label="CMS modules"><article class="card"><span class="pill">Foundation</span><h2>Pages</h2><p>Structured homepage, About, Services, Solutions and contact-page content.</p></article><article class="card"><span class="pill">Portfolio</span><h2>Projects</h2><p>HMD ERP, Congo Delivery, Moto Track and all future Dakzo case studies.</p></article><article class="card"><span class="pill">Content</span><h2>Insights</h2><p>Article records, metadata, publishing status and future editorial workflow.</p></article><article class="card"><span class="pill">Assets</span><h2>Media</h2><p>Media records are modeled now; R2 upload management arrives in Phase 3.</p></article><article class="card"><span class="pill">Safety</span><h2>Revisions</h2><p>Every future publish operation has a revision and activity-audit model from day one.</p></article><article class="card"><span class="pill">SEO</span><h2>Metadata</h2><p>Editable SEO titles, descriptions, canonical paths and social-image references are first-class content fields.</p></article></section><div class="status"><strong>CMS storage: ${status}</strong><span class="muted">Authentication is fail-closed and requires a valid Cloudflare Access JWT before this page is rendered.</span></div></main></div></body></html>`;
}

function escapeHtml(value) {
  return String(value).replace(/[&<>'"]/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
}
