export function injectPhase7Admin(response) {
  return new HTMLRewriter()
    .on('head', {
      element(element) {
        element.append(`<style>
.phase7-bar{margin-top:18px;padding:16px;border:1px solid #31506e;border-radius:14px;background:#0a1c2d}.phase7-bar strong{display:block;margin-bottom:5px}.phase7-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.phase7-live{color:#84e0b7}.phase7-draft{color:#f0d47a}.phase7-status-field{display:none!important}dialog.phase7-dialog{width:min(720px,calc(100% - 32px));max-height:80vh;overflow:auto;border:1px solid #34516f;border-radius:18px;background:#091522;color:#edf4ff;padding:0;box-shadow:0 24px 70px #000a}dialog.phase7-dialog::backdrop{background:#0009}.phase7-dialog-head{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:18px 20px;border-bottom:1px solid #263b57;position:sticky;top:0;background:#091522}.phase7-dialog-body{padding:18px 20px}.phase7-revision{display:grid;grid-template-columns:1fr auto;gap:12px;padding:14px 0;border-bottom:1px solid #20354d}.phase7-revision small{display:block;color:#91a7c0;margin-top:4px}
</style>`, { html: true });
      }
    })
    .on('body', {
      element(element) {
        element.append(`<dialog class="phase7-dialog" id="phase7-dialog"><div class="phase7-dialog-head"><div><strong>Revision history</strong><div class="muted" id="phase7-publication-summary"></div></div><button class="btn" type="button" id="phase7-close">Close</button></div><div class="phase7-dialog-body" id="phase7-revisions"></div></dialog><script>
(()=>{
const configs=[
 {type:'page',form:'page-form',id:'page-id',status:'page-status',refresh:'refresh-pages'},
 {type:'project',form:'project-form',id:'project-id',status:'project-status',refresh:'refresh-projects'},
 {type:'article',form:'article-form',id:'article-id',status:'article-status',refresh:'refresh-articles'}
];
const q=(id)=>document.getElementById(id);
function note(message){const el=q('toast');if(!el)return;el.textContent=message;el.hidden=false;clearTimeout(window.__phase7Toast);window.__phase7Toast=setTimeout(()=>{el.hidden=true},3600)}
async function call(path,options={}){const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||('Request failed ('+response.status+')'));return data}
function current(config){return q(config.id)?.value||''}
function barFor(config){return q(config.form)?.querySelector('[data-phase7-bar]')}
async function refresh(config){const id=current(config);const bar=barFor(config);if(!bar)return;const buttons=bar.querySelectorAll('button');buttons.forEach(button=>{button.disabled=!id});if(!id){bar.querySelector('[data-phase7-state]').textContent='Save this record as a draft before previewing or publishing.';return}try{const data=await call('/api/admin/publication/'+config.type+'/'+encodeURIComponent(id));const pub=data.publication;const state=bar.querySelector('[data-phase7-state]');if(pub){state.className='phase7-live';state.textContent='Live version '+pub.version+' · '+pub.live_path+' · published '+new Date(pub.published_at).toLocaleString()}else{state.className='phase7-draft';state.textContent='Draft only · no CMS publication is live yet.'}}catch(error){bar.querySelector('[data-phase7-state]').textContent=error.message}}
function addBar(config){const form=q(config.form);if(!form)return;const status=q(config.status);if(status?.closest('.field'))status.closest('.field').classList.add('phase7-status-field');form.addEventListener('submit',()=>{if(status)status.value='draft'},{capture:true});const bar=document.createElement('div');bar.className='phase7-bar';bar.dataset.phase7Bar='';bar.innerHTML='<strong>Preview & publishing</strong><div class="muted">Save first to create/update the draft. Preview shows the draft. Publish promotes exactly the saved draft to the public site.</div><div data-phase7-state class="phase7-draft">Draft status loading…</div><div class="phase7-actions"></div>';const actions=bar.querySelector('.phase7-actions');const make=(label,handler,className='btn')=>{const b=document.createElement('button');b.type='button';b.className=className;b.textContent=label;b.addEventListener('click',handler);actions.append(b);return b};make('Preview draft',()=>{const id=current(config);if(id)window.open('/admin/preview/'+config.type+'/'+encodeURIComponent(id),'_blank','noopener')});make('Publish',async()=>{const id=current(config);if(!id)return;try{const data=await call('/api/admin/publish/'+config.type+'/'+encodeURIComponent(id),{method:'POST',body:'{}'});note('Published '+data.publication.live_path+' (version '+data.publication.version+')');q(config.refresh)?.click();setTimeout(()=>refresh(config),250)}catch(error){note(error.message)}},'btn primary');make('Unpublish',async()=>{const id=current(config);if(!id||!confirm('Remove the CMS publication from the live site? The saved draft will remain.'))return;try{await call('/api/admin/unpublish/'+config.type+'/'+encodeURIComponent(id),{method:'POST',body:'{}'});note('CMS publication removed; draft kept.');q(config.refresh)?.click();setTimeout(()=>refresh(config),250)}catch(error){note(error.message)}},'btn danger');make('Revision history',()=>openRevisions(config));form.append(bar);refresh(config)}
async function openRevisions(config){const id=current(config);if(!id)return;const dialog=q('phase7-dialog'),body=q('phase7-revisions'),summary=q('phase7-publication-summary');body.replaceChildren();summary.textContent='Loading…';dialog.showModal();try{const data=await call('/api/admin/revisions?entity_type='+encodeURIComponent(config.type)+'&entity_id='+encodeURIComponent(id));summary.textContent=data.publication?'Live version '+data.publication.version+' · '+data.publication.live_path:'No CMS publication is live.';if(!(data.revisions||[]).length){body.textContent='No revisions recorded yet.';return}for(const revision of data.revisions){const row=document.createElement('div');row.className='phase7-revision';const copy=document.createElement('div');const title=document.createElement('strong');title.textContent=revision.action;const meta=document.createElement('small');meta.textContent=new Date(revision.created_at).toLocaleString()+' · '+revision.actor_email;copy.append(title,meta);const restore=document.createElement('button');restore.type='button';restore.className='btn';restore.textContent='Restore to draft';restore.addEventListener('click',async()=>{if(!confirm('Restore this revision into the editor as a draft? The live publication will not change.'))return;try{await call('/api/admin/revisions/'+encodeURIComponent(revision.id)+'/restore',{method:'POST',body:'{}'});dialog.close();q(config.refresh)?.click();note('Revision restored to draft. Review it, then publish when ready.');setTimeout(()=>refresh(config),300)}catch(error){note(error.message)}});row.append(copy,restore);body.append(row)}}catch(error){summary.textContent=error.message}}
q('phase7-close')?.addEventListener('click',()=>q('phase7-dialog').close());
for(const config of configs)addBar(config);
document.addEventListener('click',event=>{if(event.target.closest('.record-item')||event.target.closest('[data-tab]')||event.target.id==='new-project'||event.target.id==='new-article')setTimeout(()=>configs.forEach(refresh),100)});
})();
</script>`, { html: true });
      }
    })
    .transform(response);
}
